version: '3.3'

services:
  nifi:
    image: apache/nifi
    restart: always
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    ports:
      - 9090:9090
      - 9091:9091 #for web hooks (dev)
      - 9092:9092 #for web hooks (hml)
      - 9093:9093 #for web hooks (prd)
    volumes:
      - nifi:/opt/nifi
      - ./pokemon.json:/tmp/pokemon.json

  nifi-registry:
    image: apache/nifi-registry
    restart: always
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
    ports:
      - 18080:18080
      
volumes: 
  nifi:
